[package]
name = "jin"
version = "0.1.0"
edition = "2024"

[dependencies]
pancakeswap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }

alloy = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
