[package]
name = "pancakeswap"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
alloy = { workspace = true }
async-trait = { workspace = true }
ruint = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
